# Generated by Django 5.0.1 on 2024-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symtom',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
