# Generated by Django 5.0.1 on 2024-03-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_available_time_doctor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
